spring.application.name=aws-services
spring.application.isprod=false
spring.application.env=${SPRING_APPLICATION_ENV}

logback.log-colors.enabled=${LOGBACK_LOG_COLORS_ENABLED}
logback.logstash.enabled=${LOGBACK_LOGSTASH_ENABLED:false}
logback.logstash.full-host=${LOGBACK_LOGSTASH_FULL_HOST}
logback.log-type={$LOGBACK_LOG_TYPE:JSON} # types: JSON (default), TEXT, COLOR_TEXT

server.ssl.enabled=${SERVER_SSL_ENABLED:true}
server.ssl.key-store-type=PKCS12
server.ssl.key-store=${SERVER_SSL_KEY_STORE:please_set_env_var/server.ssl.key-store}
server.ssl.key-store-password=${SERVER_SSL_KEY_STORE_PASSWORD:please_set_env_var/server.ssl.key-store-password}

native.reflection-configuration-generator.enabled=${NATIVE_REFLECTION_CONFIGURATION_GENERATOR_ENABLED:false}

spring.security.oauth2.resourceserver.opaque.introspection-uri: ${OIDC_INTROSPECTION_URI}
spring.security.oauth2.resourceserver.opaque.introspection-client-id: smart_scrum_poker_aws
spring.security.oauth2.resourceserver.opaque.introspection-client-secret: smart_scrum_poker_aws

#logging.pattern.console={"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%p","logger":"%logger","message":"%m","exception":"%ex"}
