spring.application.name=aws_services
server.ssl.enabled=${SERVER_SSL_ENABLED:true}
server.ssl.key-store-type=PKCS12
server.ssl.key-store=${SERVER_SSL_KEY_STORE:please_set_env_var/server.ssl.key-store}
server.ssl.key-store-password=${SERVER_SSL_KEY_STORE_PASSWORD:please_set_env_var/server.ssl.key-store-password}

spring.security.oauth2.resourceserver.opaque.introspection-uri: https://localhost.balazskrizsan.com:4040/connect/introspect
spring.security.oauth2.resourceserver.opaque.introspection-client-id: smart_scrum_poker_aws
spring.security.oauth2.resourceserver.opaque.introspection-client-secret: smart_scrum_poker_aws
